### ISSUE TITLE
Does this repository have the same security issue as CBOR C#

### ISSUE THREAD

**Issue by jimsch** [peteroupc/CBOR-Java#7]
Does the same security issue exist here that is in the C# version for dealing with referenced objects while decoding?

**Comment by peteroupc** [comment]
Yes, the security issue applies to this repository just as it does to the C# repository.  See the [advisory](https://github.com/peteroupc/CBOR-Java/security/advisories/GHSA-mm44-wc5p-wqhq) I published.

**Comment by peteroupc** [comment]
Apparently, you might not have received automatic updates from this repository, presumably because the way the advisory ought to reference the package and package ecosystem is incorrect (is "com.upokecenter/cbor" the correct name for this package? is "Central Repository" the correct name for the ecosystem? what about "Maven"?).
